### ISSUE TITLE
Does the "1.0.0" version number have well-defined semantics?

### ISSUE THREAD

**Issue by mentalisttraceur** [christianbundy/free-public-license#2]
(Accidentally submitted incomplete issue by hitting `Shift+Enter` instead of `Shift+'`, sorry)

Not really sure if it's going to matter to anyone, but I was wondering if anyone could expect any specific meaning from the three numbers in the version? Something like SEMVER perhaps, where the first number indicated backward-incompatible changes, etc?

**Comment by christianbundy** [comment]
Yep, that's correct -- it's meant to follow semantic versioning, so small changes in wording and spelling (e.g. typo fixes) would bump it to 1.0.1, future enhancements (e.g. an express patent grant) should bump it to 1.1.0, and backward-incompatible changes (e.g. adding "every except Richard Stallman" to the license grant) would bump the major version.

I don't expect that we'll ever bump the major version, but the intention is to stick to SemVer.

**Comment by mentalisttraceur** [comment]
Great, thanks for clarifying that.

As an aside, I just wanted to let you know that I got a huge laugh out of the "hooray" reaction emoji to my initial posting of this issue, back when it was still a duplicated issue post with the incompleted title and empty body.

**Comment by mentalisttraceur** [comment]
And now, years later, I'm glad I made that previous comment here about the "hooray" reaction, and left the first duplicate issue in the state that it is.

This way I have enough context to reconstruct it in enough detail to find it lightly amusing all over again, even though I had forgotten all about it.

This is great. Validating, to see my habits of making my words capture the information needed to understand them paying off.
