### ISSUE TITLE
SemVer versioning and the "and/or" vs "and" issue

### ISSUE THREAD

**Issue by mentalisttraceur** [christianbundy/free-public-license#3]
# Issue

I'd like clarification on whether or not you consider this wording compatible/equivalent to this license:

    Permission to use, copy, modify, and distribute [...]

**Note the `and` as opposed to `and/or`.** My efforts to look into the issue (though I am not a lawyer) strongly suggest to me that they are legally equivalent and that the `/or` is a relatively modern tack-on onto the license text, attempting to clarify something that never needed clarifying (but see the large details section below on why some people disagree).

Please note that I'm not advocating that you change the license wording at this time, I'm just hoping to get clarification on where this project stands on this wording.

# Motivation

As much as I don't like wasting time talking about legalese, my main concern is that someone reads this exact license text, sans `/or`, concludes that it's somehow less permissive, and passes up using something that they might find helpful. I was hoping to mitigate that by explicitly stating that the license effective _is_ the Free Public License 1.0.0, but I don't want to do that if you think it'll cause more confusion that it fixes, or if you disagree with my assessment that they're equivalent legalese.

# Legalese Details

I'm going to document what I've learned so far here, so anyone reading this can have a better starting point for forming your own conclusions as possible - I'll try to provide an accurate/unbiased account here as much as I can. Because some legal systems place an obscene demand on disclaimers, I must again say: I'm not a lawyer, and nothing in this post should be construed to be legal _advice_, and me posting this should not be taken to create or imply an attorney-client relationship. (Did I mention I despise the legalistic mess that necessitates these disclaimers, this discussion in the first place, etc?) Anyway, here goes.

1. First, I just want to profusely sarcastically thank Washington University and whoever was in charge there back in the year 2000 or so over there for even making this an issue for any of us. Near as I can tell, it never was an issue, until someone at W.U. started asserting a ridiculous interpretation of the license text they basically copy-pasted from prior licenses (the `Permission to use, copy, modify, and distribute this software [...] is hereby granted` part). No one wanted to risk wasting resources fighting a lawsuit over it, so they didn't get properly slapped for their misdeed, and now we have a cloud of FUD around the `and distribute` wording.

2. The `Permission to use, copy, modify, and distribute this software [...] for any purpose [...] is hereby granted` wording was around in "ancestor" licenses to this one since sometime in the 1990's, possibly earlier. The earliest I was able to track down can be seen in Python: run `license()` in a Python interpreter and hit the Enter/Return key until you get to the end - the last license uses this wording.

3. I think we can agree that the wordings in question (`and` vs `and/or` in that spot) are intended to do the same thing: grant all of those permissions _independently_. So to put it very pedantically: permission to use the software is granted, permission to copy the software is granted, permission to modify the software is granted, permission to distribute the code is granted, and permission is granted to do any combination of those things.

3. Specifically, I think we can agree that `Permission to use, copy, modify, and distribute this software [...] is hereby granted` means you can modify the software, and then distribute the modified version. It might seem unreasonable to us that anyone would construe it to mean that you can modify the software, or distribute it, or copy it, but not both modify and distribute the modified derivative, and not both modify and copy the modified derivative. This, by the way, was the ridiculous interpretation that Washington University gave, according to [Debian mailing lists where this issue was discussed](https://lists.debian.org/debian-legal/2000/09/msg00007.html). It's notable that Washington University has never actually held up this position in court, nor am I aware of any rulings where such an interpretation was found to be valid. It's just that they threated to sue for modifying a distributed version, and even though courts (at least in the US) are prone to finding against the party who chose the license terms in the event of a disagreement (since they had the opportunity to chose the words to best represent what they wanted), no one had both the means and the desire to legally fight them on it.

4. When the question of the ISC license (of which this license is a verbatim subset) being approved by the OSI as "Open Source (tm)" and by the FSF as GPL-compatible, concerns about the `and` wording came up. I have not been able to track down records of these discussions, so I have no idea if there were other precise concerns or legal precedent brought up to warrant the change, or if people just remembered being weary of the same wording when Washington University decided to metaphorically pee in the community pool of licenses using that wording. This is where the change from `and` to `and/or` originated, near as I can tell.

5. At this point it's worthwhile to note that `and/or` does not have a pretty history in the precedent of English-speaking, common-law courts like those in the US, Britain, etc. You can search for keywords like "and/or in legal drafting" and find more than you would want to read about the mixed reception it gets in legal circles. It seems to have been rammed through to enough popular usage, both in courts and in layperson vernacular, that it's no longer a major issue, but there is a history of it being considered legally ambiguous. While I don't agree with their assessment and think that it's pretty apparent what it is intended to mean most of the time, including in this case, it's worth bearing in mind for the next point.

6. Some people, in particular the OpenBSD people, expressed concern about the change - their position seems to be that rather than making the license text clearer, it actually might make the license text more ambiguous in international contexts, in particular in countries where the primary legalese language isn't English and the `and/or` construct is less normalized. To understand why this is an issue, it's worth noting that license texts can conceivably be bad to either those releasing the code (if the person violates the terms of the license, and we want to hold them accountable) or those using the code (if the person releasing the code decides to turn around and claim the license didn't mean that usage). The former is unlikely to matter with FPL and ISC licenses, because the point is that we're giving others permission to do whatever, so we're not worried about them doing something we did not mean to allow. The latter concerns every code user, however: In the US, this ambiguity, even if it exists, doesn't matter too much, because if we turn around and try to sue them for infringement or something, the people who use our code can expect that the courts will likely find in their favor, since _we_ chose the license wording. But I'm not so sure about other jurisdictions in the world - maybe if a non-English court finds the `and/or` ambiguous, they'd be inclined to allow someone retroactively claiming they didn't mean to give all the permissions the benefit of the doubt? I think that's the concern, anyway - see the next point for why I think it's probably not a major issue.

7. Despite the concern raised by the OpenBSD guys, numerous licenses use the "and/or" wording, including licenses like the entire current suite of CC licenses, which have a legal team behind them striving to keep them legally internationally robust. The widespread prevalence of this construct in legal drafting makes me think it's not likely to be an issue anymore, despite some distaste for the `and/or` construct in legal circles.

# Summary

So on the one hand, I don't see it as likely being a functional change, just a stylistic one. The `and/or` camp argues that `and` by itself is ambiguous and that `and/or` more explicitly suggests that those permissions are independent of one-another. The `and` camp argues that `and/or` is ambiguous and that `and` already clearly meant the permissions were independent. Since legalese is just non-deterministic code running on grossly under-specified systems with few if any portability guarantees, it seems worth clarifying?

**Comment by christianbundy** [comment]
Interesting, thanks for all this thought (and apologies for letting it go stale!).

I think I'd like to keep the license text as-is, since it's directly copied from the ISC license (or MIT? I don't remember :sweat_smile:), but your reasoning makes sense to me.

**Comment by mentalisttraceur** [comment]
Right, I didn't want you to change the license text, just was looking to see if you agreed that the two wordings were equivalent. Sounds like you do.

At some point after I asked this here, I also emailed Rob Landley, the guy who did the Zero-Clause BSD license, and asked him the same question. He too agreed that they were equivalent.

(For anyone else reading this who doesn't know, the Zero-Clause BSD and the Free Public License 1.0.0 are the same license, same exact text, independently invented by two different people.)

Also at some point GitHub's license auto-detection started detecting both variants as 0BSD, so I think by now the issue is thoroughly settled.

Now if someone ever tries to pull what Washington University did again, the open source software community would have a lot more evidence to say: "look, there was common understanding that both the `and/or` form and the `and` form were giving the same full permissions".

Which is really good for this license, and for everyone trying to use it or rely on it. Thank you!
